// Ice King Quiz - Smart Trip Recommendation Engine

const trips = [
  { name: "Beach Chill Vibes", description: "Perfect for relaxation and sunshine", emoji: "🏖️" },
  { name: "Theme Park Chaos", description: "Maximum adventure and thrills", emoji: "🎢" },
  { name: "Nature Road Trip", description: "Explore scenic routes and landscapes", emoji: "🚗" },
  { name: "City Culture Tour", description: "Museums, food, and urban exploration", emoji: "🎭" },
  { name: "Mountain Adventure", description: "Hiking, views, and fresh air", emoji: "⛰️" },
  { name: "Luxury Spa Retreat", description: "Pure relaxation and pampering", emoji: "🧖" }
];

const iceKingLines = [
  "Gunter is judging...",
  "That's... acceptable",
  "Hmm, interesting choice",
  "Not bad, not bad",
  "CHAOS APPROVED! 🎉",
  "Even Gunter approves",
  "Bold. I like it.",
  "Ooh, sophisticated"
];

// React with random Ice King commentary
function react() {
  const randomLine = iceKingLines[Math.floor(Math.random() * iceKingLines.length)];
  document.getElementById("talk").innerText = `"${randomLine}"`;
}

// Generate trip recommendations based on user input
function getRecommendedTrips() {
  const vibe = document.getElementById("vibe").value;
  const type = document.getElementById("type").value;
  const budget = document.getElementById("budget").value;
  const activities = Array.from(document.querySelectorAll(".activity:checked")).map(el => el.value);

  let recommended = [];

  // Simple recommendation logic
  if (vibe === "chill" || type === "stay") {
    recommended.push(trips[0]); // Beach Chill
    if (activities.includes("spa")) recommended.push(trips[5]); // Spa Retreat
  }

  if (vibe === "chaos" || type === "roadtrip") {
    recommended.push(trips[1]); // Theme Park
    recommended.push(trips[2]); // Road Trip
  }

  if (activities.includes("nature")) {
    recommended.push(trips[4]); // Mountain
    recommended.push(trips[2]); // Road Trip
  }

  if (activities.includes("culture") || activities.includes("food")) {
    recommended.push(trips[3]); // City Culture
  }

  if (budget === "luxury") {
    recommended.push(trips[5]); // Spa Retreat
  }

  // Remove duplicates and return top 3
  const uniqueTrips = [...new Set(recommended.map(t => t.name))];
  const selectedTrips = uniqueTrips.slice(0, 3);

  // If we don't have 3, add random ones
  while (selectedTrips.length < 3) {
    const random = trips[Math.floor(Math.random() * trips.length)];
    if (!selectedTrips.includes(random.name)) {
      selectedTrips.push(random.name);
    }
  }

  return selectedTrips.map(name => trips.find(t => t.name === name));
}

// Show results and ranking system
function go() {
  const recommendedTrips = getRecommendedTrips();

  if (recommendedTrips.length === 0) {
    alert("Please fill out the quiz first!");
    return;
  }

  document.getElementById("quiz").classList.add("hidden");
  document.getElementById("results").classList.remove("hidden");

  let html = "";
  recommendedTrips.forEach((trip, i) => {
    html += `<div class="card">
      <h3>${trip.emoji} ${trip.name}</h3>
      <p>${trip.description}</p>
      <select id="r${i}">
        <option value="1st">1st Choice</option>
        <option value="2nd">2nd Choice</option>
        <option value="3rd">3rd Choice</option>
      </select>
    </div>`;
  });

  document.getElementById("list").innerHTML = html;
}

// Generate email with rankings
function send() {
  const vibe = document.getElementById("vibe").value;
  const type = document.getElementById("type").value;
  const must = document.getElementById("must").value;
  const recommendedTrips = getRecommendedTrips();

  let txt = "🐧 ICE KING QUIZ RESULTS 🐧\n\n";
  txt += "═══════════════════════════════════\n\n";
  txt += "YOUR TRIP RANKINGS:\n";

  recommendedTrips.forEach((trip, i) => {
    const ranking = document.getElementById("r" + i).value;
    txt += `${ranking}: ${trip.emoji} ${trip.name}\n`;
  });

  txt += "\n═══════════════════════════════════\n\n";
  txt += "QUIZ RESPONSES:\n";
  txt += `Vibe: ${vibe}\n`;
  txt += `Travel Style: ${type}\n`;
  txt += `Must-Haves: ${must || "(Not specified)"}\n`;
  txt += "\n═══════════════════════════════════\n";
  txt += "\nGenerated by Ice King Quiz 🐧";

  window.location.href = "mailto:?subject=My Ice King Quiz Results&body=" + encodeURIComponent(txt);
}

// Reset quiz
function reset() {
  document.getElementById("quiz").classList.remove("hidden");
  document.getElementById("results").classList.add("hidden");
  document.getElementById("vibe").value = "";
  document.getElementById("type").value = "";
  document.getElementById("budget").value = "";
  document.getElementById("must").value = "";
  document.querySelectorAll(".activity").forEach(el => el.checked = false);
  document.getElementById("talk").innerText = '"Answer correctly or... whatever."';
}
